[build]
  command = "rm -f package-lock.json && npm install && npm rebuild lightningcss && npm run build && npm install --force lightningcss"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  EXPO_PLATFORM = "web"
  NPM_FLAGS = "--include=optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200